### ISSUE TITLE
Space bar stops working

### ISSUE THREAD

**Issue by whale** [round/TypeSmart-beta#9] opened 2019-11-19 01:40 UTC
**Describe the bug**
I am typing, backspacing, typing, then the space bar stops working. VERY scary ;)

**Expected behavior**
I expect the keyboard to work per normal other than the awesome little doodads that I expect from SmartType

**Screenshots**
https://cl.ly/99cf5b23c79f

**Comment by MarkyCDavis** [comment] 2019-11-19 18:46
Confirmed this bug, github sucks and won’t let me upload a video so I’m texting it to you round.

**Comment by inadarei** [comment] 2019-11-20 02:25
I believe this is duplicate of #7 and is fixed by PR f17d19fd79620d81ba60c19350e081743b6d12db

**Closed as completed** 2019-11-23 22:03 UTC
Labels: bug
